fmdd_sylius_admin_sorting_index:
    path: /sorting
    defaults:
        _controller: FMDD\SyliusSortingPlugin\Controller\SortingController:index

fmdd_sylius_admin_sorting_products_save:
    path: /sorting/save
    defaults:
        _controller: FMDD\SyliusSortingPlugin\Controller\SortingController:savePositions

fmdd_sylius_admin_sorting_products:
    path: /sorting/taxon/{taxonId}
    defaults:
        _controller: FMDD\SyliusSortingPlugin\Controller\SortingController:products

